BASE_URL = "https://tobeto.com/giris"
Tobeto_Logo_XPATH = "//*[@id='__next']/div/main/section/div/div/div/div/div[1]/span/img"
EMAIL_XPATH = "/html/body/div[1]/div/main/section/div/div/div/div/form/input[1]"
PASSWORD_XPATH = "/html/body/div[1]/div/main/section/div/div/div/div/form/input[2]"
LOGIN_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
FORGOT_PASSWORD_XPATH= "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/label/small/p"
REGISTER_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div[2]/label/small/a"
SYSTEM_MESSAGE_XPATH = "//*[@id='__next']/div/div[2]/div/div[2]"
MESSAGE_Error_XPATH = "//*[@id='__next']/div/main/section/div/div/div/div/form/p"
